### ISSUE TITLE
PSF build for adsorption reservior

### ISSUE THREAD

**Issue by jpotoff** [GOMC-WSU/Workshop#4]
for some reason the following works, 
vmd  < build_psf_box_1.tcl  or ./build_psf_box_1.tcl

But this does not work (but should)
vmd -dispdev text < build_psf_box_1.tcl

**Comment by msoroush** [comment]
I think psfgen uses NAMD rather than VMD. So, as long as we did not install namd, we cannot use vmd -dispdev text < build_psf_box_1.tcl

[https://www.ks.uiuc.edu/Research/vmd/mailing_list/vmd-l/29126.html](url)

**Comment by msoroush** [comment]
The other solution is to use `package require psfgen` instead of `psfgen<<ENDMOL`.

[https://www.ks.uiuc.edu/Research/vmd/mailing_list/vmd-l/29127.html](url)
