### ISSUE TITLE
Segmentation fault when not specifying dihedral interactions

### ISSUE THREAD

**Issue by ghost** [GOMC-WSU/Workshop#6]
I'm trying to simulate toluene adsorption in EDUSIF -- I have generated the relevant topology and pdb files and subsequently generated the the psf and start_box files. I'm using the TraPPE model of toluene with no dihedrals present --- so I have removed the autogen dihedrals from the topology file and set CBMC_Dih to 0 in the .conf file. When I run the simulation i get this error;
'Segmentation fault: 11'

**Comment by YounesN** [comment]
Hi Tom,
I think your problem might be related to GOMC itself. Can you post your issue on [GOMC page](https://github.com/GOMC-WSU/GOMC/issues) and attach all of your simulation files? It will also help if you let us know if you are using master or development branch of GOMC.
Thanks.

**Comment by msoroush** [comment]
@YounesN @Tom-Pope 

We should move this to GOMC repository and not GOMC-Workshop. Here is our [conversation](https://gitter.im/GOMC_WSU/Issues?utm_source=share-link&utm_medium=link&utm_campaign=share-link) on how to fix this issue:

**Comment by YounesN** [comment]
Closing this issue and I will open another one on GOMC page.
